title: Visually Grounded Interaction and Language (ViGIL) 3.0
description: Visually Grounded Interaction and Language (ViGIL) 3.0 Workshop at NeurIPS 2019
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-144588579-1
